<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net9.0</TargetFrameworks>
    <Version>1.9.4</Version>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>Joan López</Authors>
    <Description>Core Resolver Unity is a simple wrapper for use under a Clean Architecture solution, to resolve DI references using Unity</Description>
    <RepositoryType>git</RepositoryType>
    <PackageTags>IoC DI SimpleInjector dependency resolver</PackageTags>
    <RepositoryUrl>https://github.com/topelab/Core.Resolver</RepositoryUrl>
    <PackageProjectUrl>https://github.com/topelab/Core.Resolver</PackageProjectUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SimpleInjector" Version="5.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Topelab.Core.Resolver\Topelab.Core.Resolver.csproj" />
  </ItemGroup>
</Project>